- Creational/Builder/README.md
- Creational/Builder/java/BuilderPattern.java
Proposing addition of the Builder Pattern
> Builder pattern

- Behavioral/Observer/java/CitizenObserver.java
- Behavioral/Observer/java/ObserverDesignPattern.java
- Behavioral/Observer/java/RestaurantObserver.java
- Behavioral/Observer/java/WeatherObserver.java
- Behavioral/Observer/java/WeatherSubject.java
- Behavioral/Observer/java/WeatherType.java
> Implemented Observer pattern example in Java

- Creational/Singleton/csharp/SingletonDesignPattern.cs
Added the pretty similar C# implementation for the Singleton Pattern.
> Added C# Singleton implementation

- Creational/Singleton/csharp/SingletonPattern with thread safety .net 4/SingletonPatternSample.sln
- Creational/Singleton/csharp/SingletonPattern with thread safety .net 4/SingletonPatternSample/App.config
- Creational/Singleton/csharp/SingletonPattern with thread safety .net 4/SingletonPatternSample/Program.cs
- Creational/Singleton/csharp/SingletonPattern with thread safety .net 4/SingletonPatternSample/Properties/AssemblyInfo.cs
- Creational/Singleton/csharp/SingletonPattern with thread safety .net 4/SingletonPatternSample/SingletonPatternSample.csproj
- Structural/Decorator/c#/DecoratorPattern.cs
> C#   decorator branch

- Creational/Singleton/cpp/SingletonDesignPattern.cpp
- Creational/Singleton/cpp/SingletonDesignPattern.h
- Creational/Singleton/cpp/main.cpp
Adding singleton design pattern implementation in C++.
> C++ singleton implementation

- Creational/Singleton/README.md
I saw that you had a README about the builder design pattern, but didn't have one for singleton. I tried to keep it consistent with the builder README. Let me know if you'd like me to revise anything. Thanks!
> added README for the singleton design pattern

- Behavioral/Observer/README.md
- Behavioral/Strategy/README.md
- Creational/Abstrac Factory/README.md
Wrote a few more README for the patterns
> wrote factory, strategy, and observer README files

- Creational/Method Chaining/java/MethodChaining.java
- Creational/Method Chaining/python/method_chaining.py
> Add method chaining implementation in java and python

- Structural/Adapter/java/AnimalAdapterDemo.java
- Structural/Adapter/java/ShapeAdapterDemo.java
- Structural/Bridge/java/BridgeDemo.java
- Structural/Composite/java/CompositeDemo.java
- Structural/Proxy/java/ProxyDemo.java
Small Demo for ShapeAdapter and AnimalAdapter.
> Adapter Design pattern with AnimalAdapter and ShapeAdapter

- Creational/Builder/python/BuilderPattern.py
This PR adds a python Builder pattern.
> add python builder pattern

- Structural/Facade/java/Blackberry.java
- Structural/Facade/java/FacadePatternClient.java
- Structural/Facade/java/Iphone.java
- Structural/Facade/java/MobileShop.java
- Structural/Facade/java/Samsung.java
- Structural/Facade/java/ShopKeeper.java
This PR add Facade design pattern written in Java.
> Add Facade design pattern

- Creational/Prototype/java/EmployeeRecord.java
- Creational/Prototype/java/Prototype.java
- Creational/Prototype/java/PrototypeDemo.java
This PR add Prototype design pattern written in Java.
> Add Prototype design pattern written in Java.

- .project
- Behavioral/TemplateMethod/.project
- Behavioral/TemplateMethod/README.md
- Behavioral/TemplateMethod/java/Defender.java
- Behavioral/TemplateMethod/java/Goalkeeper.java
- Behavioral/TemplateMethod/java/Midfielder.java
- Behavioral/TemplateMethod/java/Player.java
- Behavioral/TemplateMethod/java/TemplateMethodDemo.java
Added a template method pattern description and quick example of usage
> Behavioral: template Method patten

- Creational/Builder/java/ImmutableBuilderEx.java
This nested builder example allows creation of immutable instances using a nested builder!    
Written in java
> Added example for nested builder in Java

- Behavioral/Mediator/MediatorEx.java
> Added mediator pattern example

- Creational/Singleton/objective-c/Singleton.h
- Creational/Singleton/objective-c/Singleton.m
Singleton pattern implemented in Objective-C
> Objective-C Singleton.

- Behavioral/Iterator/c++11/iterator.cpp
Added Iterator Design Pattern implemented in C++11. Very similar to the one already implemented in JAVA in the repository.
> Added Iterator pattern in C++11

- FrontController/Dispatcher.java
- FrontController/FrontController.java
- FrontController/FrontControllerPatternDemo.java
- FrontController/GoHome.java
- FrontController/GoTution.java
Hi 
I have added simple Front Controller design pattern along with Dispatcher design pattern. In this example you are passing string object based on that Front controller decided what actions need to be carried out and uses Dispatcher to dispatch requests.
> added Front Controller design pattern

- Creational/Multiton/README.md
- Creational/Multiton/java/Multiton.java
- Creational/Multiton/java/MultitonTest.java
Referencing Issue #73 
Add simple [Multiton pattern](https://en.wikipedia.org/wiki/Multiton_pattern) in Java.
> Add Multiton pattern (in Java)

- Creational/Builder/javascript/README.md
- Creational/Builder/javascript/builderPattern.js
- Creational/Builder/javascript/builderPatternEs6.js
Adds examples for the Builder pattern (commonly called constructor pattern) in JavaScript.
> ADD: Add builder pattern examples for javascript in es5 and es6

- Concurrency/Balking Pattern/java/BalkingPattern.java
- Concurrency/Guarded Suspension/java/GuardedSuspension.java
Add the 'Guarded Suspension' and 'Balking Pattern' for Concurrency Design Patterns in Java
> Add two Concurrency Design Patterns - Java

- Creational/Factory/php/Book.php
> added new file in Factory Patter implemented in PHP

- Structural/Facade/README.md
> Created README for facade design pattern

- Behavioral/Observer/JavaScript/observer.js
Adds a javascript example for the observer pattern.
> Add: Adds javascript example for the observer pattern

- Creational/Builder/php/builder.php
Improved readability and IDE hinting
> Added docblock for Creational/Builder/php/builder.php

- Behavioral/TemplateMethod/php/template.php
Helps with IDE hinting when reading
> Added docblock for Behavioral/TemplateMethod/php/template.php

- Creational/Factory/d/Logger.d
Create a factory class of a logger in D.
> Factory logger example in d

- Creational/Abstract Factory/php/abstract_factory.php
Hello.
This is an implementation of the AbstractFactory pattern in PHP.
The example used is the same as the java example.
> Creational - Abstract Factory - PHP

- Structural/Facade/d/facade.d
A simple facade pattern in D. The `Resource` base class holds the interface where child classes implement the varying `read` method. When the classes are not similar and don't fit under a subclass, a `ResourceFacade` with members for each will work just as well.
> Dlang facade

- Structural/Facade/javaScript/facade.js
This is implementation of the facade design pattern on a simple example with daily tasks.
If the quality of implementation is suitable, I'd like to try to implement other patterns on js. If it is not, please let me know how can I fix it (I'm a newbie to contribution to open-source, so could make something wrong).
> Facade structural pattern implementation on javaScript on #134

- Behavioral/Command/javascript/command.js
Command design pattern implementation on JavaScript
> Command design patterns/js

- Behavioral/Command/python/command.py
Command pattern written in python
> command pattern using python

- Creational/Singleton/java/DoubleCheckSingletonPattern.java
Dear,
I try to contribute Java double check Singleton pattern implementation and example.
Please kindly review and merge my code.
Thank you.
> Double check singleton

- Creational/Value Object/README.md
- Creational/Value Object/java/ValueObject.java
- readme.md
I've added a Java version of the value object design pattern.
> Added Creationnal/ValueObject 

- .gitignore
- Creational/Singleton/kotlin/LazySingletonDesignPattern.kt
Hi,
I would like to contribute this Kotlin's creational pattern example.
Please kindly review. Thank you.
> Lazy Initialization Singleton Pattern with Kotlin

- Creational/Method Chaining/java/CreationWithFlowApi.java
The domain class is separated to the flow-api builder and can be used
after creation without knowledge the builder.
The flow-api (method chaining) is a very easy and lightweight way for creating new objects.
> Flow API in method chaining

- Behavioral/Command/kotlin/Command.kt
- Creational/Factory/kotlin/Factory.kt
Add Command and Factory in Kotlin
> Add Command and Factory in Kotlin

- Behavioral/State/kotlin/State.kt
- Behavioral/Strategy/kotlin/Strategy.kt
Add State and Strategy in Kotlin
> Add State and Strategy in Kotlin

- Creational/SimpleFactory/java/CheesePizza.java
- Creational/SimpleFactory/java/ClamPizza.java
- Creational/SimpleFactory/java/PepperoniPizza.java
- Creational/SimpleFactory/java/Pizza.java
- Creational/SimpleFactory/java/PizzaStore.java
- Creational/SimpleFactory/java/SimplePizzaFactory.java
- Creational/SimpleFactory/java/VeggiePizza.java
- Creational/SimpleFactory/java/readme.md
I added the simple factory default, which is a simpler factory, and is a cataloged standard. I added readme.md explaining
> adding the simple factory pattern to the project, along with Readme.md

- Creational/Constructor/README.md
- Creational/Constructor/javaScript/constructor.js
Adding constructor pattern for JS for pre ES2015 and ES2015+.
> add JS  Constructor pattern

- Creational/Factory/javaScript/factory.js
add JavaScript factory pattern in pre ES2015 and in ES2015+.
> add JavaScript factory pattern

- Creational/Singleton/scala/SingletonCounter.scala
> added singleton counter in scala

- Creational/Abstract Factory/java/example1/App.java
- Creational/Abstract Factory/java/example1/FactoryCar.java
- Creational/Abstract Factory/java/example1/GMCFactory.java
- Creational/Abstract Factory/java/example1/Minivan.java
- Creational/Abstract Factory/java/example1/Pickup.java
- Creational/Abstract Factory/java/example1/Savana.java
- Creational/Abstract Factory/java/example1/Sienna.java
- Creational/Abstract Factory/java/example1/Sierra.java
- Creational/Abstract Factory/java/example1/Tacoma.java
- Creational/Abstract Factory/java/example1/ToyotaFactory.java
- Creational/Abstract Factory/java/example1/readme.md
#159 
Added a new implementation for Abstract Factory.
In this implementation i create a folder called `example1` to separate the code and a `readme.md ` exclusive.
> feat(Abstract Factory): added new implementation

- Structural/Adapter/java/example1/AppAfter.java
- Structural/Adapter/java/example1/AppBofere.java
- Structural/Adapter/java/example1/Desktop.java
- Structural/Adapter/java/example1/Device.java
- Structural/Adapter/java/example1/Mobile.java
- Structural/Adapter/java/example1/Mobile.java~
- Structural/Adapter/java/example1/MobileAdapter.java
- Structural/Adapter/java/example1/Notebook.java
#159 
- new implementation for adapter
- create new folder for implementation (example1)
> Added new Implementation for Adapter in Java

- Repository/java/example1/Product.java
- Repository/java/example1/ProductRepository.java
- Repository/java/example1/ProductRepositoryDefault.java
- Repository/java/example1/Repository.java
- Repository/java/example1/RepositoryDefault.java
- Repository/java/example1/readme.md
#159 
- new implementation for Repository Pattern
**Obs:** I am writing a simple documentation about this pattern.
> Added new Implementation for Repository Pattern

- Structural/Decorator/kotlin/Decorator.kt
Decorator pattern implemented in kotlin.
> kotlin: decorator

- Behavioral/Strategy/kotlin/FunctionalStrategy.kt
Strategy pattern implemented in kotlin in functional way
> kotlin: functional strategy pattern

- Behavioral/Observer/Kotlin/observer.kt
> simple kotlin observer

- Structural/Composite/Kotlin/composite.kt
> simple kotlin composite

- Behavioral/Mediator/readme.md
Added the missing behavioral/mediator description
> Added mediator description

- Behavioral/Memento/python/memento.py
Memento implementation in python 3 using the traditional Originator - Caretaker definition of the pattern
> Added memento implementation for python 3

- Behavioral/ChainOfResponsability/C++/ChainOfResponsibility.cpp
I have added a cpp class to showcase chain of reponsibility design pattern
> added chain of reponsibility pattern in c++

- .gitignore
- Behavioral/Strategy/Swift/Strategy.swift
`.DS_Store` is a file that stores custom attributes of its containing folder, such as the position of icons or the choice of a background image. These files are created in every folder on mac, therefore they are usually specified in `.gitignore`.
> Add Strategy for Swift; Add `.DS_Store` file to `.gitignore`

- Creational/Value Object/kotlin/ValueObject.kt
note: kotlin is way nicer at Value Objects than java :P
> Added Creation/ValueObject/kotlin

- Behavioral/Interpreter/C++/InterpreterPattern.cpp
added a simple c++ class to showcase interpreter design pattern
> added interpreter pattern in cpp

- Creational/Builder/elixir/house_builder.ex
This PR adds an implementation of the builder pattern for Elixir.
> Added builder pattern for Elixir

- Behavioral/State/C++/statepattern.cpp
Added a simple cpp state design pattern example
> added state design pattern example in cpp

- Behavioral/Visitor/javascript/Visitor.js
added a simple visitor design pattern in javascript
> added visitor design pattern in javascript

- Behavioral/ChainOfResponsability/C++/ChainPattern.cpp
- Creational/Abstract Factory/cpp/abstract-factory.cpp
Adding chain of responsibility design pattern in C++
> Adding chain of responsibility design pattern in C++

- Behavioral/Mediator/kotlin/mediator.kt
> added mediator implementation on kotlin

- Behavioral/Callback/javascript/callback.js
- Creational/Constructor/python/constructor.py
I've added Constructor pattern which was missing an implementation from Python language.
> Added Contructor pattern in Python

- .gitignore
- Creational/Builder/java/Developer.java
- Creational/Builder/java/DeveloperBuildUsage.java
Add build pattern for java language
> Add build pattern for java language

- readme.md
As per title, I just added the links to the 2 Behavioral design patterns that were missing in the main README file. _(Interpreter and Mediator)_
> Add Interpreter and Mediator patterns to README.md

- Concurrency/Fan Out/kotlin/FanOutProducer.kt
Kotlin pattern of a produce/fan-out using kotlin's `Channel` and `Coroutine`
> [ADD] Kotlin concurrency using producer pattern

- Creational/Factory-Method/Java/IPizzeria.java
- Creational/Factory-Method/Java/Main.java
- Creational/Factory-Method/Java/MiPizzeria.java
- Creational/Factory-Method/Java/Pizza.java
- Creational/Factory-Method/Java/PizzaOrillaRellena.java
A pizzeria example for Java. (Spanish)
> Add factory-method Java

- Creational/Method Chaining/dlang/method_chaining.d
Method Chaining in D.
Comments on the source explaining  about Method Chaining and other way that D allow the user to use it.
> Method Chaining in D

- Structural/PrivateClass/golang/car/car.go
- Structural/PrivateClass/golang/main.go
> Add private structures for golang

- Behavioral/Callback/java/CallbackDemo.java
- Behavioral/Callback/python/callback_demo.py
Java and Python sample code for implementing callback of design patterns.
> Add Java and Python implementations for callback

- Behavioral/README.md
Summary and description for Behavioral Pattern
> README.md for behavioral pattern

- Structural/Adapter/c++/adapter.h
- Structural/Adapter/c++/dlist.h
Demonstrated adapter pattern by adapting a simple doubly-linked list to a stack. Explained using two types of adapter: object adapter, and class adapter. In-code comments were made to help with learning. #261
> Added adapter pattern for C++

- Creational/Builder/cpp/BuilderPattern.cpp
Great initiative in this project! :)
Commit part of Hacktoberfest 2019.
> Added Builder patter in C++ language

- Creational/LazyInitialization/kotlin/DeferVariableAssignment.kt
- Creational/LazyInitialization/kotlin/LazyInitializationPattern.kt
Added an example for kotlin lazy initialization pattern, one that shows race condition and one example that shows the lateinit variable deferrment. Readme was already there for the description, let me know what needs updating!
> Add Kt lazy init pattern and lateinit example

- Behavioral/Memento/kotlin/main.kts
Added an example for Kotlin memento pattern. There is an originator class that has an inner class of `Memento`. The `Memento` class has the saved state.
You can save multiple states in a list and apply them later.
> Memento design pattern in Kotlin

- Creational/Method Chaining/kotlin/main.kts
Method chaining in Kotlin is pretty simple. When using the `apply` method it will give a scope of the given context (in this example the `PersonBuilder`). Within that scope you can set examples with a lambda. When the lambda has been executed it gives back an instance of the class it was applied to. This class can execute a new method, hence the method chaining.
More information: [here](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/apply.html)
> Method chaining in Kotlin

- Behavioral/Interpreter/kotlin/interpreter.kts
- Structural/Builder/kotlin/builder.kts
> Add Builder pattern for Kotlin

- Behavioral/Interpreter/kotlin/interpreter.kts
> Add interpreter pattern for Kotlin

- Creational/SimpleFactory/kotlin/main.kts
A simple `Pizza` interface which has 2 implementations (Cheese and Pepperoni). There is a singleton factory (`PizzaStore`) which can create pizza's.
> Simple Factory method in Kotlin

- Behavioral/Interpreter/kotlin/interpreter.kts
- Structural/Builder/kotlin/builder.kts
- Structural/Repository/kotlin/repository.kts
> Add Repository pattern for Kotlin

- Structural/Bridge/java/BridgeDemo.java
- Structural/Bridge/java/Color.java
- Structural/Bridge/java/GreenColor.java
- Structural/Bridge/java/Pentagon.java
- Structural/Bridge/java/RedColor.java
- Structural/Bridge/java/Shape.java
- Structural/Bridge/java/Triangle.java
Resolving https://github.com/ZoranPandovski/design-patterns/issues/297 , create example for java bridge design pattern.
> resolving issue 297, create example for java bridge design pattern

- Creational/Singleton/java/StaticBlockSingleton.java
Resolving https://github.com/ZoranPandovski/design-patterns/issues/283 , Add Static Block Singleton Implementation for this Java Design Pattern.
> Add Static Block Singleton Implementation for this Java Design Pattern

- Structural/Bridge/python/BridgePattern.py
Hello, i made the bridge pattern in python. I hope you like it
> Adding bridge pattern in python

- Structural/Composite/python/CompositePattern.py
Hey, i adding composite pattern in python too
> Adding composite pattern in python

- Behavioral/Callback/cpp/callback.cpp
- Structural/Decorator/ruby/decorator.rb
The code was tested on an online compiler. It seems to work as expected.
> Added examples of the decorator pattern in Ruby and callback pattern in C++.

- Behavioral/Callback/README.md
Issue #83, added a bit more explanation and added a diagram for better understanding.
> Adds explanation of callback pattern

- Structural/Flyweight/python/FlyWheight.py
Hello again, i made flywheight pattern in python
> Adding flywheight pattern in python

- Behavioral/State/python/state_demo.py
Added state sample in python language to control the state of a quote.
> Add state sample in python

- Behavioral/Strategy/java/medievalstrategy/ArmyKeyAsset.java
- Behavioral/Strategy/java/medievalstrategy/MedievalStrategy.java
- Behavioral/Strategy/java/medievalstrategy/WarLord.java
- Behavioral/Strategy/java/medievalstrategy/WarStrategy.java
- Behavioral/Strategy/java/medievalstrategy/strategies/CallTheTanks.java
- Behavioral/Strategy/java/medievalstrategy/strategies/DestroyTheGate.java
- Behavioral/Strategy/java/medievalstrategy/strategies/UseTheSecretPassage.java
In this file, I add a strategy pattern in java with a warlord example
#297
> feat: add java Strategy pattern with a war strategy choice example

- Creational/Constructor/java/Constructor.java
- Creational/Constructor/java/PrivateConstructor.java
Added examples of public, overloaded and private constructors in Java
> Add constructor pattern in Java

- Behavioral/README.md
- Behavioral/State/README.md
- Behavioral/Visitor/README.md
- readme.md
All documents and references for Behavioral design are added.
As part of #329
> Behavioral design pattern docs updated

- Creational/LazyInitialization/java/transactions-history/CurrentYearLazyLoadingTransactionLogsIterator.java
- Creational/LazyInitialization/java/transactions-history/TransactionLog.java
- Creational/LazyInitialization/java/transactions-history/TransactionLogApp.java
- Creational/LazyInitialization/java/transactions-history/TransactionLogsDAO.java
> added example of lazy loading pattern for payment transactions history iterator

- Creational/Builder/java/Car.java
Hi I have submitted an example of a builder pattern in Java that helps guide the developer on which fields are mandatory and which are optional when using the builder pattern. It will also help guide auto complete functionality and throw compile time exceptions if guidelines aren't followed.
> Builder that provides compile time guidance on required fields

- Concurrency/Observer/php/Observable.php
- Concurrency/Observer/php/Observer.php
- Concurrency/Observer/php/Test.php
Signed-off-by: Karol Krupinski <karolkk01@gmail.com>
> add php observer implementation

- Behavioral/Callback/Ruby/callback.rb
Shows a callback in a familiar way for better understanding and in the idiomatic way, which is preferable to be used
> Adds Ruby callback example

- Concurrency/Creational/Singleton/java/DoubleCheckSingletonPattern.java
See https://en.wikipedia.org/wiki/Double-checked_locking#Usage_in_Java
(J2SE 5.0 subsection)
> Fix Java double-checked locking

- Behavioral/Mediator/scala/MediatorExample.scala
> Adding design patterns in Scala

- Creational/Factory/C++/factory.cpp
- Creational/Factory/C++/factory.h
- Creational/Factory/README.md
Created C++ implementation of the factory design pattern and updated readme with some usage and cautionary information.
> Add C++ Factory

- Behavioral/Callback/kotlin/CallbackDemo.kt
- The first example of callback pattern in Kotlin was kept
- I've added two more examples of callback pattern with Kotlin using **High Order Functions**
> Add more callback pattern examples with Kotlin

- Structural/Adapter/ruby/README.md
- Structural/Adapter/ruby/adapter.rb
Example for the Adapter pattern in Ruby language.
> Adapter pattern in Ruby

- Creational/Factory/ruby/README.md
- Creational/Factory/ruby/factory.rb
Implement Factory Pattern in Ruby language.
> Ruby Factory pattern example

- Behavioral/Delegation/kotlin/delegation2.kt
- This PR adds an second example of **delegation pattern** using Kotlin and it's powers
> Add second example of delegation pattern in Kotlin

- Behavioral/Observer/Kotlin/observer2.kt
- Add a new example of observer pattern without using Java's Observable
- It uses Kotlin's Delegates Observable
> Add a new example of observer pattern using Kotlin's delegate

- Structural/Decorator/cpp/decorator.cpp
> Added decorator example in cpp.

- Behavioral/Observer/typescript/observer.ts
- Behavioral/Strategy/typescript/strategy.ts
- Creational/Builder/typescript/buider.ts
- Structural/Decorator/typescript/decorator-experimental.ts
- Structural/Repository/typescript/repository.ts
Hello! Well, here are some examples of patterns written in the TypeScript language. Among them, the most interesting is the decorator that adds the experimental functionality of Typescript for use by decorators through notations like in Java. That's it, thanks!
> Add examples ts

- Creational/Singleton/java/AboutSingleton.txt
- Creational/Singleton/java/SingletonEager.java
- Creational/Singleton/java/SingletonSimple.java
- Creational/Singleton/java/SingletonSynchronizedBlock.java
- Creational/Singleton/java/SingletonSynchronizedMethod.java
Provided details about the Singleton Design Pattern in Java and implemented beginner-friendly versions for Singleton classes and its variations.
> Added easier Singleton implementations

- Creational/Method Chaining/README.md
- Creational/ObjectPool/README.md
Added documentation for Method Chaining and ObjectPool Design Pattern. 
This finished documentation for Creational Design Patterns.
> Added Method Chaining and ObjectPool documentation #329

- Creational/Factory-Method/python/FactoryMethod.py
Hi, i add the factory method pattern in python.
> Adding factory method in python

- Behavioral/Delegation/pyhton/delegation.py
Hi, i made the delegation pattern in python.
> Adding delegation pattern in python

- Behavioral/Visitor/python/visitor.py
Hey, today I made visitor pattern in python
> Adding visitor pattern in python

- Creational/ObjectPool/python/ObjectPool.py
Helllo again, i made the object pool pattern in python too.
> Adding Object pool pattern in python

- Concurrency/ThreadPull/go/Readme.md
- Concurrency/ThreadPull/go/threadpool.go
Hi Creator,
I have added a simple program to implement thread pool in golang.
Added readMe.md. Followed all guidelines for contribution.
Pls revert if any changes needed.
> Concurrency with threadpool

- Concurrency/Mutex/Mutex/go/mutex.go
Hi @ZoranPandovski 
**Added concurreny pattern with mutex in golang**
I have followed all the guidelines to contribute in this repository.
Please revert in case of any changes needed.
I am first time contributor for Hackoctober fest , It will be great help if u can encourage me & accept my contribution.
> added concurrency mutex example in golang

- Concurrency/Fan In/go/fanIn.go
- Concurrency/Fan In/go/readme.md
Hi @ZoranPandovski
Added concurreny pattern with fan In example in golang
I have followed all the guidelines to contribute in this repository.
Please revert in case of any changes needed.
I am first time contributor for Hackoctober fest , It will be great help if u can encourage me & accept my contribution.
> added concurrency fan in example in golang

- Concurrency/ThreadPool/java/ThreadPool.java
Added a simple implementation of a Thread Pool in Java leveraging a blocking queue.
> Added thread pool for Java

- Architectural patterns/model-view-controller/JavaScript/controller.js
- Architectural patterns/model-view-controller/JavaScript/index.html
- Architectural patterns/model-view-controller/JavaScript/model.js
- Architectural patterns/model-view-controller/JavaScript/view.js
- Architectural patterns/model-view-controller/readme.md
Hey @ZoranPandovski, I added a new architectural pattern. Kindly have a look.
> 📦 NEW: Add MVC architecutral pattern

- Creational/Method Chaining/Golang/Method_Chaining.go
Implementation of method chaining design pattern in golang
> Method chaining design pattern in golang

- Creational/Factory-Method-PT[BR]/factory_method.py
- Creational/Factory-Method-PT[BR]/readme.md
All the steps are explained inside the README that I've created it.
> Adding the Factory method design pattern in Portuguese

- readme.md
Hi @ZoranPandovski, [refactoring.guru](https://refactoring.guru/design-patterns) is a great website with fancy diagrams of design patterns. 
Could you consider merging this PR to add this site to the resources section of README?
> add site to resources section of README

- Creational/Factory-Method/php/maria-factory-method.php
Signed-off-by: Maria Papadopoulou <1maria.papa@gmail.com>
Issue: #452 
Changes:
I added a second factory method for PHP.
> Add second php factory method

- Structural/Flyweight/scala/Flywheight.scala
Hi, i added the Flyweight Pattern in scala.
> Adding Flywheight Pattern in scala
